apiVersion: v1
kind: Secret
metadata:
  name: remotec-secrets
  namespace: remotec
type: Opaque
stringData:
  # Database connection
  connectionstring-default: "Server=remotec-sqlserver;Database=RemoteCDb;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=true"
  
  # Redis connection
  connectionstring-redis: "remotec-redis:6379,abortConnect=false"
  
  # Azure AD
  azure-tenant-id: "YOUR_TENANT_ID"
  azure-client-id: "YOUR_CLIENT_ID"
  azure-client-secret: "YOUR_CLIENT_SECRET"
  
  # Storage
  azure-storage-connection: "DefaultEndpointsProtocol=https;AccountName=YOUR_ACCOUNT;AccountKey=YOUR_KEY;EndpointSuffix=core.windows.net"
  
  # Encryption
  encryption-master-key: "YOUR_BASE64_ENCODED_MASTER_KEY"
  
  # JWT
  jwt-secret-key: "YOUR_JWT_SECRET_KEY_MIN_64_CHARS"